name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Job 1: Build the project
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Java JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Step 3: Build the project with Maven
      - name: Build with Maven
        run: mvn -B clean compile

  # Job 2: Run tests (dependent on build job)
  test:
    runs-on: ubuntu-latest
    needs: build  # Ensure that the 'build' job runs successfully before 'test'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Run the tests
      - name: Run tests with Maven
        run: mvn test

      # Generate code coverage report with JaCoCo
      - name: Generate Code Coverage Report
        run: mvn jacoco:report

  # Job 3: Package the application (dependent on test job)
  package:
    runs-on: ubuntu-latest
    needs: test  # Ensure that the 'test' job runs successfully before 'package'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Package the project into a JAR
      - name: Package JAR
        run: mvn package

      # Save the generated JAR as an artifact (optional)
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v3
        with:
          name: currency-conversion
          path: target/*.jar